workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get
          flutter precache --ios
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build IPA
        script: |
          # El secreto es el flag --no-codesign para evitar el error de certificados
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
