workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get dependencies
        script: flutter packages pub get
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
