workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get
          flutter precache --ios
      - name: Install Pods
        script: |
          cd ios
          # Limpiamos rastros de instalaciones previas
          rm -rf Pods
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          pod deintegrate
          pod install --repo-update
      - name: Build IPA
        script: |
          # Limpiamos el build de flutter antes de compilar el IPA
          flutter clean
          flutter packages pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
