workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get
          flutter precache --ios
      - name: Install Pods
        script: |
          cd ios
          # Limpieza total de instalaciones previas
          rm -rf Pods
          rm -f Podfile.lock
          pod deintegrate
          pod install --repo-update
      - name: Build IPA
        script: |
          # Limpiamos el proyecto de Flutter antes de la compilación final
          flutter clean
          flutter packages pub get
          # Forzamos la regeneración del archivo que fallaba
          flutter build ios --config-only --no-codesign
          # Compilación final
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
