workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60

    scripts:
      - name: Clean & Get dependencies
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Install Pods
        script: |
          flutter pub get
          flutter build ios --no-codesign

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
