workflows:
  ios-workflow:
    name: Build iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get
          flutter precache --ios
      - name: Install Pods
        script: |
          # 1. Generamos la configuración necesaria ANTES de instalar pods
          flutter build ios --config-only --no-codesign
          
          # 2. Entramos a la carpeta de iOS y limpiamos rastros viejos
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod deintegrate
          
          # 3. Instalamos las dependencias nativas
          pod install --repo-update
      - name: Build IPA
        script: |
          # Construimos el archivo final (IPA)
          # No usamos 'flutter clean' aquí para mantener la configuración del paso anterior
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
